name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: git config --global user.email "actions@users.noreply.github.com"
      - run: git config --global user.name "${{ github.actor }}"
      - run: npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
      - run: npm install
      - run: npm version ${{ github.event.inputs.semver }}
      - run: |
          echo "Requesting OTP from Optic..."
          otp=$(curl -s https://optic-zf3votdk5a-ew.a.run.app/api/generate/dkv0r0auw)
          npm publish --otp
