name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: salmanm/auto-publish@main
        with:
          github-token: ${{secrets.github_token}}
          npm-token: ${{secrets.NPM_TOKEN}}
          optic-token: ${{secrets.OPTIC_TOKEN}}
          actor-name: ${{ github.actor }}
          actor-email: "actions@users.noreply.github.com"
          semver: ${{ github.event.inputs.semver }}
